version: "3"
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres
 
  elasticsearch:
    restart: always
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}


volumes:
  elastic-data:
    driver: local

networks:
  postgres:
    driver: bridge